export const dataExample = [
  { id: 1, name: "Robenia" },
  { id: 2, name: "Emelda" },
  { id: 3, name: "Ardine" },
  { id: 4, name: "Coraline" },
  { id: 5, name: "Myra" },
  { id: 6, name: "Bessy" },
  { id: 7, name: "Muffin" },
  { id: 8, name: "Katerine" },
  { id: 9, name: "Faber" },
  { id: 10, name: "Catina" },
  { id: 11, name: "Ilario" },
  { id: 12, name: "Jacklyn" },
  { id: 13, name: "Kathryn" },
  { id: 14, name: "Osmund" },
  { id: 15, name: "Lorelle" },
  { id: 16, name: "Ivor" },
  { id: 17, name: "Bevon" },
  { id: 18, name: "Hy" },
  { id: 19, name: "Ninnetta" },
  { id: 20, name: "Lindy" },
  { id: 21, name: "Wald" },
  { id: 22, name: "Siward" },
  { id: 23, name: "Tony" },
  { id: 24, name: "Amalea" },
  { id: 25, name: "Derrek" },
  { id: 26, name: "Oliviero" },
  { id: 27, name: "Way" },
  { id: 28, name: "Olivia" },
  { id: 29, name: "Allianora" },
  { id: 30, name: "Carly" },
  { id: 31, name: "Darleen" },
  { id: 32, name: "Wilfred" },
  { id: 33, name: "Lutero" },
  { id: 34, name: "Zachery" },
  { id: 35, name: "Sanderson" },
  { id: 36, name: "Marilyn" },
  { id: 37, name: "Laryssa" },
  { id: 38, name: "Lisa" },
  { id: 39, name: "Alissa" },
  { id: 40, name: "Pamelina" },
  { id: 41, name: "Evey" },
  { id: 42, name: "Humfrey" },
  { id: 43, name: "Lorri" },
  { id: 44, name: "Bernelle" },
  { id: 45, name: "Oliviero" },
  { id: 46, name: "Kimmi" },
  { id: 47, name: "Deeanne" },
  { id: 48, name: "Kissiah" },
  { id: 49, name: "Tove" },
  { id: 50, name: "Luella" },
  { id: 51, name: "Darsey" },
  { id: 52, name: "Samuel" },
  { id: 53, name: "Krystalle" },
  { id: 54, name: "Otes" },
  { id: 55, name: "Harper" },
  { id: 56, name: "Stacee" },
  { id: 57, name: "Paula" },
  { id: 58, name: "Lissy" },
  { id: 59, name: "Emmalyn" },
  { id: 60, name: "Dido" },
  { id: 61, name: "Dana" },
  { id: 62, name: "Cleveland" },
  { id: 63, name: "Tatiania" },
  { id: 64, name: "Audi" },
  { id: 65, name: "Alon" },
  { id: 66, name: "Annabella" },
  { id: 67, name: "Baudoin" },
  { id: 68, name: "Wiley" },
  { id: 69, name: "Erwin" },
  { id: 70, name: "Kathleen" },
  { id: 71, name: "Mikey" },
  { id: 72, name: "Charyl" },
  { id: 73, name: "Myer" },
  { id: 74, name: "Emilio" },
  { id: 75, name: "Marge" },
  { id: 76, name: "Lorry" },
  { id: 77, name: "Lacee" },
  { id: 78, name: "Morgana" },
  { id: 79, name: "Nola" },
  { id: 80, name: "Emilio" },
  { id: 81, name: "Hallsy" },
  { id: 82, name: "Alana" },
  { id: 83, name: "Earle" },
  { id: 84, name: "Isacco" },
  { id: 85, name: "Bonni" },
  { id: 86, name: "Parrnell" },
  { id: 87, name: "Sylas" },
  { id: 88, name: "Niels" },
  { id: 89, name: "Zaccaria" },
  { id: 90, name: "Tomaso" },
  { id: 91, name: "Jarred" },
  { id: 92, name: "Darla" },
  { id: 93, name: "Valentino" },
  { id: 94, name: "Tobiah" },
  { id: 95, name: "Ursulina" },
  { id: 96, name: "Erminie" },
  { id: 97, name: "Gaylor" },
  { id: 98, name: "Linn" },
  { id: 99, name: "Lorri" },
  { id: 100, name: "Franzen" },
];

export const dataExampleAsync = [
  { id: 1, name: "Robenia", image: "/images/image1.png" },
  { id: 2, name: "Emelda", image: "/images/image2.png"},
  { id: 3, name: "Ardine", image: "/images/image3.png" },
  { id: 4, name: "Coraline", image: "/images/image2.png"},
  { id: 5, name: "Myra" , image: "/images/image3.png"},
  { id: 6, name: "Bessy", image: "/images/image1.png" },
  { id: 7, name: "Muffin", image: "/images/image2.png" },
  { id: 8, name: "Katerine", image: "/images/image3.png" },
  { id: 9, name: "Faber", image: "/images/image1.png" },
  { id: 10, name: "Catina", image: "/images/image2.png" },
]

export function getDataAsync() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(dataExampleAsync)
    }, 2000)
  })
}