import Head from "next/head";
import Cards from "@/components/cards";
import Dropdown from "@/components/Dropdown";
import { dataExample, dataExampleAsync, getDataAsync } from "@/helpers";
import { useEffect, useState } from "react";

export default function Home() {
  const [asyncData, setAsyncData] = useState([]);
  const [open, setOpen] = useState(false);
  const loading = open && asyncData.length === 0;

  useEffect(() => {
    getDataAsync()
    .then(data =>
      setAsyncData(data)
    );
  }, [loading]);

  useEffect(() => {
    if(!open) setAsyncData([])  
  }, [open])  

  return (
    <>
      <Head>
        <title>Auto Complete</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="flex h-screen w-screen p-6 items-center justify-center">
        <Cards>
          <Dropdown title="Async Search" data={dataExample} disabled={false} />
          <Dropdown
            title="Sync Search"
            data={asyncData}
            setOpen={() => {setOpen(true)}}
            setClose={() => {setOpen(false)}}
            loading={loading}
            disabled={false}
          />
        </Cards>
      </div>
      {/* <Example /> */}
    </>
  );
}
